name: Some CI/CD Pipeline

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
    tags:
      - v*
  schedule:
    # 4am every Saturday
    - cron: '0 4 * * 6'

defaults:
  run:
    shell: bash

jobs:
  raw-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        arch: [amd64]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2      

      - name: Echo variables
        run: bash ci/environment-variables.bash
        env: 
          OS_NAME: ${{ matrix.os }}
          CPU_ARCH: ${{ matrix.arch }}

  build-binaries:
    if: (github.event_name == 'pull_request') || startsWith(github.ref, 'refs/tags/') || (github.ref == 'refs/heads/main')
    needs: raw-testing
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64]
        python-version: [3.9]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Echo variables
        run: bash ci/environment-variables.bash
        env: 
          OS_NAME: ${{ matrix.os }}
          CPU_ARCH: ${{ matrix.arch }}

  create-tag:
    if: github.ref == 'refs/heads/main'
    needs: build-binaries
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create Tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main

  create-release-draft:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: Release for PR ${{ github.event.number }} on Actions run ${{ github.run_id }} via commit ${{ github.sha }}
          draft: true
